spring:
  application:
    name: demo-service
  jmx:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8082